import Foundation

class AdvancedPlanGenerator {
    
    // ASC Logic Implementation
    
    func generateProgram(goal: PlanGoal, selectedDays: Set<Int>, duration: Int, level: ExperienceLevel, equipment: Set<String>, ownerId: String) -> TrainingProgram {
        
        let daysCount = selectedDays.count
        // 1. Logik: Split Selection based on Days
        let split = determineSplit(days: daysCount)
        
        // 2. Logik: Build Routines for Split
        var routines: [TrainingTemplate] = []
        
        for (dayName, focus) in split.schedule {
            let routine = buildRoutine(focus: focus, goal: goal, duration: duration, level: level, equipment: equipment, ownerId: ownerId)
            routines.append(routine)
        }
        
        // 3. Logik: Assign Schedule
        // Map the generated routines to the SPECIFIC selected weekdays
        // Sort days (e.g. 2, 4, 6) to ensure order
        let sortedDays = selectedDays.sorted()
        var schedule: [Int: String] = [:]
        
        // Cycle through routines to fill the selected days
        for (index, day) in sortedDays.enumerated() {
            // Use modulo if we have fewer routines than days (repeat) 
            // or fewer days than routines (some routines won't fit? - logic ensures split matches day count usually)
            if !routines.isEmpty {
                let routine = routines[index % routines.count]
                schedule[day] = routine.id
            }
        }
        
        return TrainingProgram(
            id: UUID().uuidString,
            title: "\(goal.rawValue) Plan (\(daysCount) Tage)",
            description: "Personalized \(level.localizedTitle(AppSettings())) plan focussing on \(focusString(goal)). Generated by Adaptive Coach.",
            difficulty: mapDifficulty(level),
            durationWeeks: 4, // Default Mesocycle
            routines: routines,
            schedule: schedule
        )
    }
    
    private func determineSplit(days: Int) -> (name: String, schedule: [(String, String)]) {
        switch days {
        case 2: return ("Full Body", [("A", "Full Body"), ("B", "Full Body")])
        case 3: return ("Full Body", [("A", "Full Body"), ("B", "Full Body"), ("C", "Full Body")])
        case 4: return ("Upper/Lower", [("Upper A", "Upper"), ("Lower A", "Lower"), ("Upper B", "Upper"), ("Lower B", "Lower")])
        case 5: return ("Upper/Lower/PPL", [("Upper", "Upper"), ("Lower", "Lower"), ("Push", "Push"), ("Pull", "Pull"), ("Legs", "Legs")])
        case 6: return ("PPL x2", [("Push A", "Push"), ("Pull A", "Pull"), ("Legs A", "Legs"), ("Push B", "Push"), ("Pull B", "Pull"), ("Legs B", "Legs")])
        default: return ("Hybrid", [("Full Body", "Full Body")])
        }
    }
    
    private func buildRoutine(focus: String, goal: PlanGoal, duration: Int, level: ExperienceLevel, equipment: Set<String>, ownerId: String) -> TrainingTemplate {
        // Here we would strictly filter an Exercise Database. 
        // For now, we generate placeholder templates that *claim* to use available equipment.
        
        var exercises: [String] = []
        let count = duration / 10 // Approx exercises
        
        // Logic: Select movement patterns based on Focus
        // E.g. Upper -> Push, Pull (Vertical/Horizontal)
        
        if focus.contains("Upper") || focus.contains("Push") {
            if hasEquipment(equipment, ["barbell", "bench"]) {
                exercises.append("Bankdrücken (Langhantel)")
            } else if hasEquipment(equipment, ["dumbbell", "bench"]) {
                exercises.append("Bankdrücken (Kurzhantel)")
            } else {
                exercises.append("Liegestütze")
            }
            exercises.append("Schulterdrücken")
        }
        
        if focus.contains("Upper") || focus.contains("Pull") {
             if hasEquipment(equipment, ["pullup_bar"]) {
                exercises.append("Klimmzüge")
            } else if hasEquipment(equipment, ["lat_pulldown"]) {
                exercises.append("Latzug")
            } else {
                exercises.append("Rudern (Kurzhantel)") // Fallback
            }
        }
        
        if focus.contains("Lower") || focus.contains("Legs") || focus.contains("Full Body") {
             if hasEquipment(equipment, ["barbell", "rack"]) {
                exercises.append("Kniebeugen (Langhantel)")
            } else if hasEquipment(equipment, ["dumbbell"]) {
                exercises.append("Goblet Squats")
            } else {
                exercises.append("Air Squats")
            }
            
            if hasEquipment(equipment, ["barbell"]) {
                exercises.append("Kreuzheben")
            }
        }
        
        // Fill up
        while exercises.count < count {
            exercises.append("Accessory Exercise \(exercises.count + 1)")
        }
        
        return TrainingTemplate(
            id: UUID().uuidString,
            name: "\(focus) Training",
            exercises: exercises,
            ownerId: ownerId,
            updatedAt: Date()
        )
    }
    
    // Helper to check if ANY of the required sets are fully satisfied
    // Simplified: Check if *any* of the keywords exist in user selection
    private func hasEquipment(_ userEquipment: Set<String>, _ required: [String]) -> Bool {
        // In real app, we map IDs. Here we check if user equipment contains *any* match or if we assume implicit simple bodyweight.
        // For Movo, we need to map the internal IDs.
        // Assuming userEquipment contains IDs like "dumbbell", "barbell".
        // If 'required' is ["barbell", "bench"], user needs ALL.
        // But for this generator's simple logic:
        
        for req in required {
            if !userEquipment.contains(req) { return false } // Strict requirement
        }
        return true
    }
    

    
    private func focusString(_ goal: PlanGoal) -> String {
        switch goal {
        case .hypertrophy: return "Hypertrophy"
        case .strength: return "Strength"
        case .endurance: return "Endurance"
        case .weightLoss: return "Metabolic Conditioning"
        }
    }
    
    private func mapDifficulty(_ level: ExperienceLevel) -> TrainingProgram.ProgramDifficulty {
        switch level {
        case .beginner: return .beginner
        case .intermediate: return .intermediate
        case .advanced: return .advanced
        }
    }
}
